[build]
	publish = "_site"
	command = "npm run build"

[[redirects]]
	from = "/blog/"
	to = "/archive/"
	status = 301
	force = true

[[redirects]]
	from = "/twitter"
	to = "https://twitter.com/vanzasetia"
	status = 301
	force = true

[[redirects]]
	from = "/mastodon"
	to = "https://mastodon.social/@vanzasetia"
	status = 301
	force = true

[[redirects]]
	from = "/linkedin"
	to = "https://www.linkedin.com/in/vanzasetia/"
	status = 301
	force = true

[[redirects]]
	from = "/github"
	to = "https://github.com/vanzasetia"
	status = 301
	force = true

[[redirects]]
	from = "/frontendmentor"
	to = "https://www.frontendmentor.io/profile/vanzasetia"
	status = 301
	force = true

[[redirects]]
  from = "https://vanzasetia.netlify.app"
  to = "https://vanzasetia.site"
  status = 301
  force = true
